// All reusable variables here
#let myLang = "it"
#let myName = "Aldo Bettega"
#let myMatricola = "2101087"
#let myTitle = "Sviluppo di una piattaforma evidence-based per la prioritizzazione delle vulnerabilità mediante analisi del rischio e contesto operativo"
#let myDegree = "Tesi di Laurea"
#let myUni = "Università degli Studi di Padova"
#let myDepartment = "Dipartimento di Matematica ''Tullio Levi-Civita''"
#let myFaculty = "Corso di Laurea in Informatica"
#let profTitle = "Prof. "
#let myProf = "Eleonora Losiouk"
#let myCompany = "Kirey S.r.l."
#let myTutor = "Stefano Marchetti & Malik Giafar Mohamed"
#let myLocation = "Padova"
#let myAA = "2025-2026"
#let myTime = "Settembre 2026"